apiVersion: apps/v1
kind: Deployment
metadata:
  name: konecty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konecty
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: konecty
    spec:
      containers:
        - name: konecty
          image: konecty/konecty:2.0.0-dev.27
          env:
            - name: MONGO_URL
              value: "mongodb://localhost:27017/konecty"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /liveness
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
