on:
    release:
        types:
            - created
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Meteor
              uses: meteorengineer/setup-meteor@v1
              with:
                  meteor-release: '1.5'
            - name: Build
              run: |
                  export NODE_TLS_REJECT_UNAUTHORIZED=0
                  meteor npm install
                  meteor build --server-only /tmp/build
            - name: Copy build to GitHub
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: /tmp/build/Konecty.tar.gz
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Get the tag name
              run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: konecty/konecty:${{ env.TAG }}
                  build-args: |
                    VERSION=${{ env.TAG }}

